### ISSUE TITLE
need to fix php error notice "Use of undefined constant WP_ENV - assumed 'WP_ENV'"

### ISSUE THREAD

**Issue by aryeharmon** [AmitT/podium#1]
When errors are turned on i get this error.

Notice: Use of undefined constant WP_ENV - assumed 'WP_ENV' in C:\xampp\htdocs\podium\wp-content\themes\podium\functions.php on line 19

Notice: Use of undefined constant WP_ENV - assumed 'WP_ENV' in C:\xampp\htdocs\podium\wp-content\themes\podium\functions.php on line 25

What is WP_ENV for? it does not seem that it has a value of any kind.

**Comment by AmitT** [comment]
used for us to defind our current environment (dev, prod etc...).
in the wp-config.php `add define('WP_ENV', 'development');`
will use this to run the right gulp tasks  & loading the right files.

wee need to give it a default value if it's not defined. 
somthing like:
`
if (!defined('WP_ENV')) {
  // Fallback if WP_ENV isn't defined in your WordPress config
  // Used in lib/assets.php to check for 'development' or 'production'
  define('WP_ENV', 'production');
}
`

**Comment by aryeharmon** [comment]
Great fixed. I added it to the functions.php file.

**Comment by aryeharmon** [comment]
Seems like functions.php is called before wp-config.php
So i get this error when i define WP_ENV also in my wp-config file:
Notice: Constant WP_ENV already defined in C:\*****\*****\wp-config.php on line 82

However i noticed that it is part of the read me that we have to add the 
`define('WP_ENV', 'development');` so might not be such a big deal.

**Comment by aryeharmon** [comment]
i added the `define('WP_ENV', 'development');` on the functions.php page before the:
``
if (!defined('WP_ENV')) {
  // Fallback if WP_ENV isn't defined in your WordPress config
  // Used to check for 'development' or 'production'
  define('WP_ENV', 'production');
}
``
this solved the issue.
