### ISSUE TITLE
include detect mobile php class

### ISSUE THREAD

**Issue by aryeharmon** [AmitT/podium#14]
We need to include the detect mobile class so that we can display smaller images to mobile users.
Need to also think of a way that we wont have to check every single page load. maybe a session or a cookie?

The class may be useful for other stuff besides for images in the future.

**Comment by AmitT** [comment]
Should be a good solution for mobile menu too.

**Comment by AmitT** [comment]
Resolved by using wp_is_mobile(), WP Responsive Images, & WP add_image_size().
