### ISSUE TITLE
gulp watch task should run the styles task first time run

### ISSUE THREAD

**Issue by aryeharmon** [AmitT/podium#24]
what do you think about the watch task running the styles and rtl styles first time run?
that would prevent us from having to run the 'gulp' command before the 'gulp watch' command

gulp.start('styles');
what do you think?
should i implement it?

**Comment by AmitT** [comment]
You can try, I think it will be great.

**Comment by AmitT** [comment]
In which project you use this?

**Comment by aryeharmon** [comment]
i still did not use it inside a project, however i tested it with a project i do at home.
i pushed it to the develop branch.

**Comment by AmitT** [comment]
Thanks, I'll test & merge it to the master.
