### ISSUE TITLE
edit readme file change define('WP_ENV', 'development'); requirements

### ISSUE THREAD

**Issue by aryeharmon** [AmitT/podium#4]

**Comment by AmitT** [comment]
ADDED.
needs a rephrase.

**Comment by aryeharmon** [comment]
how about from:

Don't forget to remove this line from functions.php file:
`define('WP_ENV', 'development');`
before your theme uploaded to the production server.

to:
Once your site is ready for production, remove or comment out the following line form the functions.php file:
`define('WP_ENV', 'development');`
